# SPDX-PackageName: rf-tools
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/rf-tools
# SPDX-FileComment: tmux config
# SPDX-FileCopyrightText: © 2017 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

set-option -g prefix C-a
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-left "#[fg=green]#h:#S "
set-option -g status-right " #[fg=red]#(bash -i -c '__tmux_status_host' 2>/dev/null || echo '?') #[fg=yellow]#(python3 -c \"import os; print('{:0.02f}/{:0.02f}/{:0.02f}'.format(*os.getloadavg()))\") #[fg=blue]%H:%M#[default]"
set-window-option -g window-status-current-style bg=red

bind-key C-a last-window
bind-key a send-prefix
set -s escape-time 0
